### PR TITLE
Ros2

### PR DESCRIPTION
**Pull request by Timple**
As per suggestion: https://github.com/tilk/rtcm_msgs/pull/3#discussion_r922080159

### CODE REVIEW

**Comment by Timple** [comment]
Subtle ping.
Please bump release in the package.xml and add a tag afterwards on master :tulip:

**Comment by RyanTheRobothead** [comment]
@tilk sorry to pester, but any chance of this getting merged?

**Comment by tilk** [comment]
The build fails on the build farm, and the output is not helpful for me to determine why. Any ideas?

https://build.ros2.org/job/Fbin_ubv8_uFv8__rtcm_msgs__ubuntu_focal_arm64__binary/9/display/redirect

**Comment by RyanTheRobothead** [comment]
Hmm, you're right, that error output is pretty difficult to extract anything useful from. Given that it's a cmake command that seems to be failing, is it possible it's related to the bump of the cmake minimum required version?

**Comment by Timple** [comment]
Ah, it might be the `uint8`? Which perhaps should be a `std_msgs/UInt8` just like the header.

**Pull request merged**
