### PR TITLE
Make ros_environment a build_depend

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

This should resolve the current build failure, like https://build.ros2.org/job/Rbin_uJ64__rtcm_msgs__ubuntu_jammy_amd64__binary/49/consoleFull

### CODE REVIEW

**Comment by tilk** [comment]
Finally, it builds! Thanks for the PRs.

**Comment by clalancette** [comment]
Fantastic, thanks for merging this.

Do you mind doing a release on Foxy, Galactic, Humble, and Rolling?  I think this should finally make it build on the buildfarm.  Thanks.

**Comment by clalancette** [comment]
Thanks for doing the releases!  :crossed_fingers: that this builds now :).

**Comment by tilk** [comment]
Unfortunately, this was premature - I received more build failures. On some builds, [cmake complains about ros_environment](https://build.ros2.org/job/Rbin_uJ64__rtcm_msgs__ubuntu_jammy_amd64__binary/53/console):
```
07:11:56 CMake Error at CMakeLists.txt:4 (find_package):
07:11:56   By not providing "Findros_environment.cmake" in CMAKE_MODULE_PATH this
07:11:56   project has asked CMake to find a package configuration file provided by
07:11:56   "ros_environment", but CMake did not find one.
07:11:56 
07:11:56   Could not find a package configuration file provided by "ros_environment"
07:11:56   with any of the following names:
07:11:56 
07:11:56     ros_environmentConfig.cmake
07:11:56     ros_environment-config.cmake
07:11:56 
07:11:56   Add the installation prefix of "ros_environment" to CMAKE_PREFIX_PATH or
07:11:56   set "ros_environment_DIR" to a directory containing one of the above files.
07:11:56   If "ros_environment" provides a separate development package or SDK, be
07:11:56   sure it has been installed.
```
I tried just removing this dependency, but it looks like [it's important for discerning ROS 1 and ROS 2 in cmake](https://discourse.ros.org/t/why-not-exposing-ros-version-in-the-ros-1-2-build-farms/25476/6).

Unfortunately, I currently don't know why this happens.

**Comment by clalancette** [comment]
> Unfortunately, this was premature - I received more build failures. On some builds, [cmake complains about ros_environment](https://build.ros2.org/job/Rbin_uJ64__rtcm_msgs__ubuntu_jammy_amd64__binary/53/console):

So it looks like you did a release with this change in place (1.1.3), and even opened up all of the rosdistro PRs, but never gave them a chance to be merged.  Could you explain why?  I think that this is enough, but we never got a try on the buildfarm.

**Comment by Timple** [comment]
Ah, I dropped them. As I assumed 1.1.4 would replace them.

**Pull request merged**
